### ISSUE TITLE
Undefined method downcase

### ISSUE THREAD

**Issue by Asimk21** [bbc/device_api-android#80] opened 2015-11-23 16:54 UTC
Undefined method downcase for nil class

/home/hive/.rvm/gems/ruby-2.2.0/gems/device_api-android-1.2.0/lib/device_api/android.rb:39

Probably because device was unavailable.

**Comment by jonpwilson** [comment] 2016-03-22 13:28
This hasn't been seen since and multiple updates to the gems have occurred in between. Closing this issue, please re-open if the issue is seen again.

**Closed by jonpwilson** 2016-03-22 13:28 UTC
